# Generated by Django 5.0 on 2026-03-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название объекта приложения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объект приложения',
                'verbose_name_plural': 'Объекты приложения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PermissionRoleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('read_permission', models.BooleanField(default=False, verbose_name='Чтение объектов')),
                ('read_all_permission', models.BooleanField(default=False, verbose_name='Чтение любых объектов')),
                ('create_permission', models.BooleanField(default=False, verbose_name='Создание объекта')),
                ('update_permission', models.BooleanField(default=False, verbose_name='Редактирование объекта')),
                ('update_all_permission', models.BooleanField(default=False, verbose_name='Редактирование любых объектов')),
                ('delete_permission', models.BooleanField(default=False, verbose_name='Удаление объекта')),
                ('delete_all_permission', models.BooleanField(default=False, verbose_name='Удаление любых объектов')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.businesselement', verbose_name='Объект приложения')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа роли',
                'verbose_name_plural': 'Правила доступа ролей',
                'ordering': ('role__name', 'element__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='permissionrolerule',
            constraint=models.UniqueConstraint(fields=('role', 'element'), name='unique_role_element'),
        ),
    ]
